# Generated by Django 3.1.6 on 2021-02-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='account.state'),
        ),
    ]
