# Generated by Django 3.1.6 on 2021-03-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'End Budget',
                'verbose_name_plural': 'End Budgets',
            },
        ),
        migrations.CreateModel(
            name='StartBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Start Budget',
                'verbose_name_plural': 'Start Budgets',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='end_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_user', to='account.endbudget'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_user', to='account.startbudget'),
        ),
    ]
