# Generated by Django 3.1.6 on 2021-03-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210303_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employed',
        ),
    ]
