# Generated by Django 3.1.6 on 2021-04-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20210408_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
