# Generated by Django 3.1.6 on 2021-02-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
